### ISSUE TITLE
Current build for premade does not include the latest vorp_core update adding support for bans

### ISSUE THREAD

**Issue by adamdrakon** [outsider31000/VORP-Premade-server#12]
For example, [vorp_resources]/vorp_core/server/sv_loadusers.lua line 30 is indeed still missing a value in the sql query.
That's why a bunch of people are reporting issues despite "running a fresh install of the premade".

**Comment by outsider31000** [comment]
Premade sql and vorp have not been update

**Comment by outsider31000** [comment]
So theres no way it would give errors . And if they update to the core then must follow the instructions in discord

**Comment by outsider31000** [comment]
As it says in the version check

**Comment by outsider31000** [comment]
I wont update untill its proven stable.

**Comment by adamdrakon** [comment]
Well I dunno where people are getting the extra column in their database table then...
